### ISSUE TITLE
Browserify for UT does not recognize import path

### ISSUE THREAD

**Issue by u0xaa55** [jamespamplin/plugin-ng-template#1]
Hi James,

Thank you for this great job, I'm using your plugin on all of my projects.

I'm facing an absolutely logical problem when I want to write unit tests for my controllers: browserify complains that it cannot find './template.html!ng-template'. This is certainly due to the "!ng-template" suffix but I don't know how to fix it.

Any clue?

**Comment by jamespamplin** [comment]
@astrinxit66 did you fix your issue? This plugin is designed for SystemJS. There may be others that will work with browserify.
